name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: run tests
        run: cargo test

      - name: build
        run: cargo build --features test_env_executables

  static-binaries-and-debfile:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: prerequisites for .deb build
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pandoc

      - name: prerequisites for .deb test
        run: |
          sudo apt-get install -y --no-install-recommends libemail-simple-perl

      - name: build static binaries
        run: |
          make static

      - name: archive static binaries
        uses: actions/upload-artifact@v4
        with:
          name: rattomail-static-binaries
          path: static_binaries

      - name: build .deb file
        run: |
          make deb

      - name: test .deb file
        run: |
          make docker-test

      - name: archive .deb file
        uses: actions/upload-artifact@v4
        with:
          name: rattomail-deb-file
          path: '*.deb'

      - name: tar up static binary for release
        run: |
          make tgz

      # needs 'Read and write permissions' to be set under
      # github / actions / general / Workflow permissions.

      - name: Create draft release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "Version ${{ github.ref_name }}"
          draft: true
          files: |
            *.tgz
            *.deb
          fail_on_unmatched_files: true
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


